#!/bin/bash
# file with commands to generate documentation, _ indicates a privately accessed file

# delete any previously generated content
rm -rf autogenerated_source

# delete any previously generated pages
rm -rf build

# generate content
python3 generate_src_rst_files.py "$@"

# generate pages from content
python3 sphinx-build.py -Q -b html autogenerated_source build

find build/_images -type f -name "*[0-9].png" -delete
python3 correct_built_html_files.py
