#!/bin/bash
rm -rf autogenerated_source
rm -rf build
python3 generate_src_rst_files.py "$@"
python3 sphinx-build.py -Q -b html autogenerated_source build
find build/_images -type f -name "*[0-9].png" -delete
python3 correct_built_html_files.py
